### ISSUE TITLE
Restore auto emails

### ISSUE THREAD

**Issue by Colin-Suckow** [osu-cascades/exhibit-x-web#30]
Google broke our gmail integration right before a presentation, so max had to remove it in commit b20b2d2. We need to figure out what caused the issue, and restore email service.

**Comment by MaxTheMitchell** [comment]
I got the emails to work again by enabling "less secure app access" on the exhbitxdev gmail account. However, the less secure app access will not longer be available past May 30, 2022. So a new means of sending emails will need to implemented at some point. For the time being I've wrapped the email sending in try-catch blocks.

**Comment by ybakos** [comment]
Yes.

So, the "new way" is to:
1) enable 2fa, so that you can
2) generate app passwords

This is a common idiom that most of the service providers are following these days.

Dig into how to generate an app password w/ gmail and you'll get it worked out.
